### ISSUE TITLE
Issue handling Timeout

### ISSUE THREAD

**Issue by ryan-ph** [goodmami/mrs-to-penman#1]
https://github.com/goodmami/mrs-to-penman/blob/765e28bbf2b08e46904da82a9e552513cb0d4c82/mrs_to_penman.py#L49

Should be changed to append '--timeout' and str(args.timeout) separately rather than appending a list of the two to cmdargs.

**Comment by goodmami** [comment]
Thanks! I think `cmdargs.extend(...)` would work just as well. I've committed that change, but I'm not set up to test on this machine. Can you confirm if it works?

**Comment by ryan-ph** [comment]
Yea, that also seems to work! Thanks.

**Comment by goodmami** [comment]
@ryanp97 Thanks for confirming!
